### ISSUE TITLE
what is chrome cache?

### ISSUE THREAD

**Issue by gabri25ele** [thomasloupe/CleanSweep2#10]
but in particular who is chrome? 
this is discrimination towards the best browsers, i.e. the non-chrome ones.

**Comment by thomasloupe** [comment]
Feel free to submit a PR with additional browser support!

**Comment by thomasloupe** [comment]
Firefox already has a feature to automatically clear cache in its settings. There is no need to add this feature to CleanSweep2.
You can learn how to do so by visiting [this link](https://support.mozilla.org/en-US/kb/how-clear-firefox-cache#w_automatically-clear-the-cache), which is directly from Mozilla. CleanSweep2 only support Chromium browsers.

Since Firefox handles itself, and all Chromium browsers are already covered by CleanSweep2, this leaves the least-used browsers in the world off the list.  If you want support for a specific browser, I would recommend opening a new issue with a specific browser request feature addition by name.
